# mkdocs.yml
site_name: "Trendy"
site_author: "Capybaras AI"
site_description: "A python tool for google trend"
site_url: "https://capybarasai.github.io/trendy"
repo_url: "https://github.com/capybarasai/trendy"
edit_uri: "blob/main/docs/"
repo_name: "capybarasai/trendy"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/capybaras-ai-logo.png
  logo: assets/capybaras-ai-logo.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
      watch:
        - docs


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - "Tutorials":
    - "Introduction": tutorials/index.md
    - "Use SerpAPI": tutorials/use_serpapi.md
    - "Aggregate Data": "tutorials/aggregate_trends.md"
  - References:
    - "Introduction": references/index.md
    - "Utilities":
      - "Utilities - Config": references/utilities/config.md
      - "Utilities - Storage": references/utilities/storage.md
      - "Utilities - Request": references/utilities/request.md
    - "SERPAPI":
      - "SERPAPI - Config": references/use_serpapi/config.md
      - "SERPAPI - Trends": references/use_serpapi/get_trends.md
    - "Manual":
      - "Manual - Config": references/manual/config.md
      - "Manual - Trends": references/manual/get_trends.md
    - "Aggregate":
      - "Aggregate - Config": references/aggregate/config.md
      - "Manual - Agg": references/aggregate/agg.md
    - "PyTrends":
      - "Manual - Config": references/use_pytrends/config.md
      - "Manual - Trends": references/use_pytrends/get_trends.md
  - "Changelog": changelog.md
